#app.yaml
runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: root
  CLOUD_SQL_PASSWORD: 
  CLOUD_SQL_DATABASE_NAME: deployment
  CLOUD_SQL_CONNECTION_NAME: mlops-282008:us-central1:deployment-001
